### ISSUE TITLE
Change item prices from API

### ISSUE THREAD

**Issue by eknowles** [SilentSys/SCEP#1]
https://github.com/SilentSys/SCEP/blob/master/SteamEnhancement/SCEP.vb#L474

Since it may be that the item is not on sale currently on the market, this endpoint will give out recent transaction

GET http://steamcommunity.com/market/priceoverview/?country=US&currency=1&appid=730&market_hash_name=UMP-45%20%7C%20Scorched%20(Field-Tested)

Results in `{"success":true,"lowest_price":"&#36;0.04","volume":"456","median_price":"&#36;0.03"}`

**Comment by SilentSys** [comment]
Interesting. It's much cleaner. Thanks for bringing this up. It will definitely be incorporated into the next update.

I thought http://steamcommunity.com/market/pricehistory/ was the only way.

**Comment by SilentSys** [comment]
It has been implemented.

Thank you.

**Comment by ElPresidentePro** [comment]
hello my name is presi and i have a problem in this file https://github.com/D3uxx/csgojackpotV2/blob/master/cost.php when is the problem here?
pls help
